### ISSUE TITLE
null is not an object (evaluating '_this.dropDownAlertRef.closeAction')

### ISSUE THREAD

**Issue by prox2** [WrathChaos/react-native-internet-connection-alert#1] opened 2021-02-20 13:09 UTC
I am getting this error when I close the internet to test it and then in console log it keep pushing infinite number of this error:
```
Possible Unhandled Promise Rejection (id: 220):
TypeError: Network request failed
```

**Comment by kuraydev** [comment] 2021-02-20 14:01
Hello @prox2,

Can you share with me a reproducible example?

**Comment by prox2** [comment] 2021-02-20 15:08
here is my code I just wrapped it with the app stuck 
```
<PaperProvider theme={theme}>
            <InternetConnectionAlert
                onChange={(connectionState) => {
                    console.log("Connection State: ", connectionState);
                    setIsInternetAvailable(connectionState.isConnected);
                }}
            >
                <AuthContext.Provider value={authContext}>
                    <PushNotificationManager>
                        <NavigationContainer theme={theme}>        
                                        <RootStackScreen />
                        </NavigationContainer>
                    </PushNotificationManager>
                </AuthContext.Provider>
            </InternetConnectionAlert>
        </PaperProvider>
```

**Comment by prox2** [comment] 2021-02-20 15:09
> here is my code I just wrapped it with the app stuck
> 
> ```
> <PaperProvider theme={theme}>
>             <InternetConnectionAlert
>                 onChange={(connectionState) => {
>                     console.log("Connection State: ", connectionState);
>                     setIsInternetAvailable(connectionState.isConnected);
>                 }}
>             >
>                 <AuthContext.Provider value={authContext}>
>                     <PushNotificationManager>
>                         <NavigationContainer theme={theme}>        
>                                         <RootStackScreen />
>                         </NavigationContainer>
>                     </PushNotificationManager>
>                 </AuthContext.Provider>
>             </InternetConnectionAlert>
>         </PaperProvider>
> ```

and yes I am using android platform

**Comment by kuraydev** [comment] 2021-02-20 16:06
@prox2 I cannot reproduce the error with this example, have you tried the official example?

**Comment by prox2** [comment] 2021-02-20 16:18
> @prox2 I cannot reproduce the error with this example, have you tried the official example?

Excatly what i did i just followed what in the example

**Comment by kuraydev** [comment] 2021-02-20 17:20
I will try to run the example on Android, let me test it

**Comment by prox2** [comment] 2021-02-21 03:21
@WrathChaos  thanks appreciate that

**Comment by prox2** [comment] 2021-02-21 03:46
i think i found out what is the problem for the error  `Possible Unhandled Promise Rejection (id: 220):
TypeError: Network request failed ` as in my app I am using fetch api and it is normal to throw network  request failed when no internet connection but for the error `null is not an object (evaluating '_this.dropDownAlertRef.closeAction') ` i still have no idea

**Comment by ghost** [comment] 2021-03-16 17:53
@prox2  i got same error and fixed by linking react-native-dropdownalert

**Comment by Garamani** [comment] 2021-05-25 17:37
Same Error:

> TypeError: null is not an object (evaluating '_this.dropDownAlertRef.closeAction')

It seems there is a problem with the Wix react-native-navigation. when I set it at root level, there is also another error mentioning:

> Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in SetRootScreens (created by ConnectFunction)

**Comment by matthewbal** [comment] 2021-06-12 12:15
+1, I got exactly the same error trying to use this library on a react native app with navigation. 
I just deleted it from the sim, yarn installed, pod installed, then rebuilt the app and this issue went away.

**Closed as completed** 2022-01-26 15:52 UTC
Labels: bug
